In [34]:
from tensorflow.keras.preprocessing.text import one_hot

In [35]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [36]:
## Define the vocabulary size
voc_size=10000
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [37]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2903, 1533, 5479, 4267],
 [2903, 1533, 5479, 3270],
 [2903, 3770, 5479, 3167],
 [588, 5552, 6078, 1616, 1801],
 [588, 5552, 6078, 1616, 9728],
 [3184, 2903, 9828, 5479, 4106],
 [6393, 8598, 4008, 1616]]

In [38]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [39]:
import numpy as np

In [40]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2903 1533 5479 4267]
 [   0    0    0    0 2903 1533 5479 3270]
 [   0    0    0    0 2903 3770 5479 3167]
 [   0    0    0  588 5552 6078 1616 1801]
 [   0    0    0  588 5552 6078 1616 9728]
 [   0    0    0 3184 2903 9828 5479 4106]
 [   0    0    0    0 6393 8598 4008 1616]]


In [41]:
## feature representation
dim=10

In [42]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step


array([[[-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.04540494, -0.04326111,  0.04285559, -0.0492935 ,
         -0.02082852,  0.0210076 , -0.03627461,  0.04905483,
         -0.04450932,  0.03798306],
        [ 0.02749241,  0.02099302, -0.0213989 ,  0.01828806,
          0.00942714, -0.01959836,  0.01104284,  0.03551494,
         -0.00452437,  0.03471306],
        [ 0.04728467, -0.0398142 , -0.02460198, -0.0

In [45]:
embedded_docs[0]

array([   0,    0,    0,    0, 2903, 1533, 5479, 4267], dtype=int32)

In [47]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[[-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.04540494, -0.04326111,  0.04285559, -0.0492935 ,
         -0.02082852,  0.0210076 , -0.03627461,  0.04905483,
         -0.04450932,  0.03798306],
        [ 0.02749241,  0.02099302, -0.0213989 ,  0.01828806,
          0.00942714, -0.01959836,  0.01104284,  0.03551494,
         -0.00452437,  0.03471306],
        [ 0.04728467, -0.0398142 , -0.02460198, -0.0

In [53]:
print(embedded_docs[0].shape) 
print(np.array([embedded_docs[0]]).shape) 

(8,)
(1, 8)


In [54]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[[-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.0109839 , -0.02448984,  0.03369557,  0.01958844,
          0.00857861, -0.04203583, -0.03231397,  0.0021488 ,
          0.03346557,  0.04145148],
        [-0.04540494, -0.04326111,  0.04285559, -0.0492935 ,
         -0.02082852,  0.0210076 , -0.03627461,  0.04905483,
         -0.04450932,  0.03798306],
        [ 0.02749241,  0.02099302, -0.0213989 ,  0.01828806,
          0.00942714, -0.01959836,  0.01104284,  0.03551494,
         -0.00452437,  0.03471306],
        [ 0.04728467, -0.0398142 , -0.02460198, -0.0